### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by NaNraptor** [LukBukkit/chartist-plugin-tooltip#2]
This JS fiddle doesn't seem to be working:[( https://jsfiddle.net/AlexanderKozhevin/aapycL87/ )]

I tried implementing it too, which didn't work either.

By not working I mean no tooltip get's displayed on hover/click or any other action

**Comment by LukBukkit** [comment]
I'll look into it, but the resources used on the fiddle are looking outdated. I try to rebuild it

**Comment by LukBukkit** [comment]
Sorry but I guess I don't have a lot of spare time in the next week. I'll to do this as soon as possible.

**Comment by LukBukkit** [comment]
I'm currently on vacation and I'm going to look into the issue when I'm home again.

**Comment by LukBukkit** [comment]
Hey,
I've googled a little bit and found this issue [chartist-plugin-tooltip#127](https://github.com/tmmdata/chartist-plugin-tooltip/issues/127) about the jsfiddle you've mentioned. It's deals with the same problem as this issue (the fiddle doesn't work).

The user @clottman has created a [version](https://jsfiddle.net/aapycL87/178/) which works by updating the libraries and removing unnecessary code. I've took her version and updated the libraries again and it still works: https://jsfiddle.net/g16kv5s2/1/

And here's the example which (I guess) wants to archive a custom hover effect: https://jsfiddle.net/h8wys0tp/2/. I've had edit the code a little bit, because the `data.element.replace(circle);` call prevents the tooltip plugin from working.

**Comment by LukBukkit** [comment]
Okay I worked a little bit more on the issue and why there are problems when using `.replace`. Everything relates to this pull request [chartist-plugin-tooltip#72](https://github.com/tmmdata/chartist-plugin-tooltip/pull/72). If you are using `ct-area` or `ct-line` as a replacement for your data point it'll get ignored by the css rule.

Here's a corrected version of the fiddle, you've linked: https://jsfiddle.net/9gzqnrd8/9/
Thanks again for your attention and I'll update the README.me soon

**Comment by LukBukkit** [comment]
If something doesn't work as expected please reopen this issue.
